apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "policy-simulator.fullname" . }}-frontend
  labels:
    {{- include "policy-simulator.labels" . | nindent 4 }}
    {{- include "policy-simulator.frontend.selectorLabels" . | nindent 4 }}
spec:
  {{- if not .Values.frontend.autoscaling.enabled }}
  replicas: {{ .Values.frontend.replicas }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "policy-simulator.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "policy-simulator.frontend.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: "{{ .Values.global.imageRegistry }}{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.frontend.port }}
              protocol: TCP
          env:
            - name: NEXT_PUBLIC_API_URL
              value: "http://{{ include "policy-simulator.fullname" . }}-backend:{{ .Values.backend.port }}"
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 10
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
