{{- if (index .Values "kube-prometheus-stack" "enabled") }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "policy-simulator.fullname" . }}-backend
  labels:
    {{- include "policy-simulator.labels" . | nindent 4 }}
    {{- include "policy-simulator.backend.selectorLabels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "policy-simulator.backend.selectorLabels" . | nindent 6 }}
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
{{- end }}
